name: docker image ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{github.repository_owner}}/immich-go